//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceReference4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/order_servicelibrary")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int oIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cId {
            get {
                return this.cIdField;
            }
            set {
                if ((this.cIdField.Equals(value) != true)) {
                    this.cIdField = value;
                    this.RaisePropertyChanged("cId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foodName {
            get {
                return this.foodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.foodNameField, value) != true)) {
                    this.foodNameField = value;
                    this.RaisePropertyChanged("foodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int oId {
            get {
                return this.oIdField;
            }
            set {
                if ((this.oIdField.Equals(value) != true)) {
                    this.oIdField = value;
                    this.RaisePropertyChanged("oId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.Iorder")]
    public interface Iorder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iorder/AddOrder", ReplyAction="http://tempuri.org/Iorder/AddOrderResponse")]
        void AddOrder(client.ServiceReference4.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iorder/AddOrder", ReplyAction="http://tempuri.org/Iorder/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(client.ServiceReference4.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iorder/RemoveOrder", ReplyAction="http://tempuri.org/Iorder/RemoveOrderResponse")]
        void RemoveOrder(int oId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iorder/RemoveOrder", ReplyAction="http://tempuri.org/Iorder/RemoveOrderResponse")]
        System.Threading.Tasks.Task RemoveOrderAsync(int oId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IorderChannel : client.ServiceReference4.Iorder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IorderClient : System.ServiceModel.ClientBase<client.ServiceReference4.Iorder>, client.ServiceReference4.Iorder {
        
        public IorderClient() {
        }
        
        public IorderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IorderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IorderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IorderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddOrder(client.ServiceReference4.Order order) {
            base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(client.ServiceReference4.Order order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public void RemoveOrder(int oId) {
            base.Channel.RemoveOrder(oId);
        }
        
        public System.Threading.Tasks.Task RemoveOrderAsync(int oId) {
            return base.Channel.RemoveOrderAsync(oId);
        }
    }
}
